### ISSUE TITLE
The Docker container is in an "unhealthy" state

### ISSUE THREAD

**Issue by hello-22-world** [edgd1er/nordvpn-proxy#43] opened 2024-09-27 18:48 UTC
2024-09-27 18:45:38: INFO: OPENVPN: UP: STARTING DANTE: 
2024-09-28 02:45:38: INFO:: ########################################################
2024-09-28 02:45:38: INFO: DANTE: WAITING FOR TUN0 TO BE UP: 
2024-09-28 02:45:38: INFO: DANTE: CHECK CONFIGURATION SOCKS PROXY: 
2024-09-28 02:45:38: INFO: DANTE: SET CONFIGURATION SOCKS PROXY: 
Sep 28 02:45:38 (1727462738.550469) sockd[217]: info: Dante/server[1/2] v1.4.3 running
Sep 28 02:45:38 (1727462738.557235) sockd[219]: info: Dante/server[2/2] v1.4.3 running
ok: run: dante: (pid 192) 0s, normally down
2024-09-27 18:45:38: INFO: OPENVPN: UP: STARTING TINYPROXY: 
2024-09-28 02:45:38: INFO: TINYPROXY: SET CONFIGURATION INT_IP: 172.xx.0.2/ EXT_IP: xxx.xxx.xxx.xx / LOG LEVEL: ERROR / LOCAL NETWORK: 172.xx.0.0/24: 
2024-09-28 02:45:38: INFO: TINYPROXY: STARTING: 
ok: run: tinyproxy: (pid 261) 1s, normally down
Initialization Sequence Completed

The error persists even though Docker has started and the proxy is working.

**Comment by edgd1er** [comment] 2024-09-28 05:11
healthcheck.sh is exiting with a 1 status.
proxy is the name of the service in docker compose, please adapt if you are running the container with docker command.

Could you run: `docker compose exec -it proxy bash /etc/service/openvpn/healthcheck.sh`

if nothing is printed, run it with -x: `docker compose exec -it proxy bash -x /etc/service/openvpn/healthcheck.sh`

**Comment by hello-22-world** [comment] 2024-09-28 16:43
It has been fixed by the update.. Thank you so much.

**Comment by hello-22-world** [comment] 2024-10-03 06:00
proxy bash -x /etc/service/openvpn/healthcheck.sh

I have identified a problem where the VPN's exiting IP does not match the connecting IP, causing it to remain in an unhealthy state.

**Comment by hello-22-world** [comment] 2024-10-03 18:40
Can it randomly connect to one of the servers if EXIT_WHEN_IP_NOTASEXPECTED=1? The best server is always the one with a different outgoing address, which causes the Docker to become unhealthy and restart by the monitor. 
=[

**Comment by edgd1er** [comment] 2024-10-04 21:12
the server ip is extracted from the ovpn file.
Although, I'm not sure that check is accurate. I think I will remove it as remote server ip is not, most of the time the exit server nor belong to the exit network.

As for the unhealthy state, It should be gone with that faulty check removed.
When nordvpn removed then api check's endpoint that could confirm or not the protected status, I had no other method to replace that check.

**Comment by edgd1er** [comment] 2024-10-05 06:10
I ve pushed a new image where status is based on nordvpn status.

**Comment by hello-22-world** [comment] 2024-10-05 06:20
Thanks so much for taking the time to look into the issue. 
Your help in identifying and fixing the problem is greatly appreciated!
I'm going to test the new fix now.
Thanks again!

**Comment by hello-22-world** [comment] 2024-10-05 06:32
> I ve pushed a new image where status is based on nordvpn status.
The "new fix" seems to have some problems. 
The Docker container keeps restarting itself when EXIT_WHEN_IP_NOTASEXPECTED = 1.

195.201.14.xxx'
+ [[ 0 -eq 0 ]]
+ msg='SERVAIL expected not found.'

+ [[ -z sigok.rsa2048-sha256.ippacket.stream.
195.201.14.xxx ]]
+ [[ -n SERVAIL expected not found. ]]
+ log 'WARNING: HEALTHCHECK: DNSSEC: SERVAIL expected not found.'

bash -x /etc/service/openvpn/healthcheck.sh+ listen_ip4=172.xx.0.2
++ getEthIp
++ jq -r '.[].addr_info[0].local'
++ ip -j -4 a show eth0
+ current_ip4=172.xx.0.2
+ [[ ! -z 172.xx.0.2 ]]
+ [[ ! -z 172.xx.0.2 ]]
+ [[ 172.xx.0.2 != 172.xx.0.2 ]]
+ checkproxies -s
+ [[ -s =~ -s ]]
+ FAILED=0
++ TCF=/run/secrets/TINY_CREDS
++ [[ -f /run/secrets/TINY_CREDS ]]
++ TCREDS=
++ curl -4 -sm 10 -x http://xxxxxxxxxxx:8888 https://ifconfig.me/ip
+ IP=

**Comment by edgd1er** [comment] 2024-10-05 08:47
> * 
> 
> 
> If I don't use this option (EXIT_WHEN_IP_NOTASEXPECTED = 1), the container remains in a "starting" state. I've changed the port 8888 on TINYPORT. Could this be causing the problem?

you 've found the cause, the wrong variable was checked for the port (both http and sock).

**Comment by hello-22-world** [comment] 2024-10-05 18:14
> > If I don't use this option (EXIT_WHEN_IP_NOTASEXPECTED = 1), the container remains in a "starting" state. I've changed the port 8888 on TINYPORT. Could this be causing the problem?
> 
> you 've found the cause, wrong variables were set for the port (both http and sock). I've commited a new image although, the healthcheck is staying in starting.

It seems that when I connect to the US server, it often connects to "us9019.nordvpn.com" and then gets stuck in a starting state.
If I change the server to CA, it quickly becomes "healthy." However, I don't understand why this happens.

**Comment by edgd1er** [comment] 2024-10-05 19:12
Healthcheck has a timeout set to 10sec.
When I ran healthcheck with the time command, total execution time most of the time was over 10.
Keeping a timeout so near to that value will give an inaccurate container's status.
I pushed a new image with a timeout set to 30sec.

**Comment by edgd1er** [comment] 2024-10-13 13:48
I close the issue as the fix looks ok. Feel free to reopen if needed.

**Closed by edgd1er** 2024-10-13 13:48 UTC
